version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3m
      timeout: 10s
      retries: 3
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080